### ISSUE TITLE
[New Module] Delegates

### ISSUE THREAD

**Issue by nephros** [Pretty-SFOS/opal#6]
I have begun preliminary work on a `Delegates` module, available at

https://github.com/nephros/opal-delegates.git

which has the goal to create ready-made view delegates.

It is in very early stages, but I open this issue to discuss feedback on what
would be required to get this into a shape ready for inclusion into Opal.

Please test and comment! ;)

**Comment by ichthyosaurus** [comment]
(If there's anything to translate I'll add the module to the new [Weblate project](https://hosted.weblate.org/projects/opal) once hosting is approved.)

**Comment by ichthyosaurus** [comment]
now included in the gallery
